/*  File generated by: Map Ed v0.98.5 */

#include "types.h"

#define bgPaletteLen 32
extern const u16 bgPalette[16];

#define bgTilesLen 128
extern const u16 bgTiles[64];

#define bgMapLen 4096
extern const u16 bgMap[2048];

