/*  File generated by: Map Ed v0.98.5 */

#include "types.h"

extern const u16 bgPalette[256];
extern const u16 bgTiles[672];
extern const u16 bgMap[4096];
extern const u16 bgCollision[4096];
