/*  File generated by: Map Ed v0.98.5 */

#define bgSkyboxPaletteLen 16
extern const u16_t bgSkyboxPalette[16];

#define bgSkyboxTilesLen 224
extern const u16_t bgSkyboxTiles[112];

#define bgSkyboxMapLen 2048
extern const u16_t bgSkyboxMap[1024];

#define bgPlatformsPaletteLen 16
extern const u16_t bgPlatformsPalette[16];

#define bgPlatformsTilesLen 448
extern const u16_t bgPlatformsTiles[224];

#define bgPlatformsMapLen 2048
extern const u16_t bgPlatformsMap[1024];

